# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(choices=[('VA', 'Villa Allende'), ('RO', 'Rosario'), ('HU', 'Hurlingham'), ('CR', 'Campo de la rivera'), ('VL', 'Villa Libertador'), ('MU', 'Muller')], default='VA', max_length=2)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=80)),
                ('barrio', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField(max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=80, null=True)),
                ('telefonoFijo', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
