# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_clase_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='titulo',
            field=models.CharField(default='vacio', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clase',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='sede',
            field=models.CharField(choices=[('VA', 'Villa Allende'), ('RO', 'Rosario'), ('HU', 'Hurlingham'), ('CR', 'Campo de la rivera'), ('VL', 'Villa Libertador'), ('MU', 'Muller')], default='VA', max_length=2),
        ),
        migrations.AlterField(
            model_name='clase',
            name='tipo',
            field=models.CharField(choices=[('DS', 'Devolucion solidaria'), ('CV', 'Consolidacion de valores'), ('R', 'Clase regular')], default='DS', max_length=2),
        ),
    ]
